# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1f7ef736451eb9b2f1ad029216d9ae70c5a1de8094f5cfaa7f9c9a5093934776bab7c95e6d563c9705667c7d8cea5d9a3cf99d0c845cb8c1f3427bd37f091fc

test:
  secret_key_base: 1c1a21b88dabb24623062e903fd11b66d4c7cb895d9bc8afc1ecc5795a22cc5e32310ea67ef855acc7c7b56dc4319afb9f1bb975842fb65bde9b53d74e09b857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
